### PR TITLE
Update main.rs

### PR DESCRIPTION
**Pull request by mrbuche**
Is this kind of what you were thinking?

You can get even fancier if name/language can just be fields in the Dog and Cat structs. Let me know!

### CODE REVIEW

**Comment by mrbuche** [comment]
Is having the Animal struct as part of the Dog/Cat needed? What you would do there is specify the animal field of Dog/Cat as a trait Animal that has get_name() and get_language() methods. Meaning have fields in a struct that are structs is not idiomatic -- you specify the field is something that walks like a duck, rather than a duck.

Probably want to tie together the common fields of name and language. Maybe there's a way...

It would be useful if Rust added feature to traits where you can specify whatever type you implement the trait for must have specific fields, but until then, you have to use getter methods to wrap that.

**Comment by mrbuche** [comment]
New commit is a better flavor. Two things unsatisfying:

1) Repeating fields instead of sharing them between types somehow. But I believe this is best, ways of getting around it would most likely inhibit performance.
2) The get_field methods which seem overly simple. But this is how you are able to call stuff in trait defaults and get automatic implementations of methods which is really useful.
    - This is why Rust being able to specify which fields a type has when defining a trait would be fantastic, you would be able to implement default get_field methods. Then implementing Animal for Cat and Dog would be automatic except for the get_info() which is specific to the type.

**Comment by mrbuche** [comment]
One more variant, I see what you were trying to do at the end. You can't iterate over (or even use variable indexing) the Animals struct since the types are different. No way to variable index a tuple, and while you can impl Iter for a struct (whether tuple struct or regular struct) the type of the item must all be the same.

**Comment by hovey** [comment]
Hi Michael, thanks for those iterations.  As as I look at them one at a time:

1. Commit 47d07aa: hard code of "Fido" L22 and "Sylvester" L31 for all Dog and Cat instances I don't think is what I was intending.
2. Commit b48a0c1: I like how to did the two `get_info` functions (and removed the hard codes from above).
3. Commit 6b07647: Just punctuation.
4. Commit 47c5c48: Right, struct composition is implemented, which is what I was trying to get at originally (but not OOP, which uses `is-a`; composition is used, which is `has-a`.  I will like to learn more from you on the hard-coded `animals.0.describe()`

No being able to iterate over tuples of different types was new to me.  Used to doing that in OOP, with pointers to polymorphic objects.  Was trying to get the hang of how to do that in Rust.  

I will propose a time on the calendar next week.  I think discussing this with you might be easier than trading comments on GitHub rn.

**Comment by mrbuche** [comment]
The .0 .1 etc. grabs that entry in the tuple struct, which is the same thing as a struct you just dont have to name the fields. But you cant make a loop over i and call animals.i.method() or anything so its not especially useful as far as I know. I use the tuple struct to wrap a type to add more functionality like making a Tensor wrapped around a Rust array: https://github.com/mrbuche/flavio/blob/main/src/math/tensor/rank_2/mod.rs

**Pull request closed without merging**
